import type { Director, DirectorInput, DirectorOutput, DirectorSlideCopy } from './types'

const TEMPLATES: { match: RegExp; line1: string; line2: string }[] = [
  { match: /home|today|daily|lesson/i,        line1: 'YOUR NEXT LESSON',  line2: 'READY EVERY DAY' },
  { match: /speak|voice|talk|listen/i,        line1: 'SPEAK OUT LOUD',    line2: 'WITH AI TUTORS' },
  { match: /scenario|conversation/i,          line1: 'PRACTICE REAL',     line2: 'CONVERSATIONS' },
  { match: /story|stories|read/i,             line1: 'LEARN THROUGH',     line2: 'STORIES' },
  { match: /challenge|friend|versus/i,        line1: 'CHALLENGE YOUR',    line2: 'CLASSMATES' },
  { match: /leaderboard|rank|score/i,         line1: 'CLIMB THE',         line2: 'LEADERBOARD' },
  { match: /vocab|word|saved|review|srs|memor/i, line1: 'BEAT THE',       line2: 'FORGETTING CURVE' },
  { match: /practice|hub/i,                   line1: 'PRACTICE YOUR WAY', line2: 'SOLO OR SOCIAL' },
]

function clean(s: string, banned: string[]): string {
  let o = s
  for (const b of banned) o = o.split(b).join('')
  return o.replace(/[,–—]+$/g, '').trim()
}

// No-API provider: keyword->template mapping with brand-voice guardrails.
// A solid offline fallback and a reference for what the LLM provider must return.
export class DeterministicDirector implements Director {
  async generate(input: DirectorInput): Promise<DirectorOutput> {
    const banned = input.brandVoice.banned
    const slides: DirectorSlideCopy[] = input.screenshots.map((sc) => {
      const key = `${sc.label ?? ''} ${sc.id}`
      const tpl = TEMPLATES.find((t) => t.match.test(key))
        ?? { line1: input.appProfile.name.toUpperCase(), line2: (input.appProfile.benefit || 'GET STARTED').toUpperCase() }
      return { screenshotId: sc.id, headline: { line1: clean(tpl.line1, banned), line2: clean(tpl.line2, banned) } }
    })
    return {
      order: input.screenshots.map((s) => s.id),
      slides,
      notes: ['Generated by DeterministicDirector (no API).'],
    }
  }
}
