import type { Director, DirectorInput, DirectorOutput, DirectorSlideCopy } from './types'

export interface OpenAIOptions {
  apiKey: string
  model?: string        // default 'gpt-4o-mini'
  baseUrl?: string      // OpenAI-compatible endpoint; default OpenAI
}

function strip(s: string, banned: string[]): string {
  let o = s || ''
  for (const b of banned) o = o.split(b).join('')
  return o.replace(/[,–—]+$/g, '').trim().toUpperCase()
}

// Bring-your-own-key vision Director. The key lives in the caller (browser or CLI);
// nothing is hosted. Reads the screenshots and writes a cohesive headline set.
export class OpenAIDirector implements Director {
  constructor(private opts: OpenAIOptions) {}

  async generate(input: DirectorInput): Promise<DirectorOutput> {
    const model = this.opts.model ?? 'gpt-4o-mini'
    const banned = input.brandVoice.banned
    const system =
      'You are a senior App Store / Google Play copywriter. You look at app screenshots ' +
      'and write punchy, on-brand store-listing headlines. Reply with JSON only.'
    const rules = [
      `App: ${input.appProfile.name}.`,
      input.appProfile.benefit ? `Core benefit: ${input.appProfile.benefit}.` : '',
      input.appProfile.audience ? `Target audience: ${input.appProfile.audience}.` : '',
      input.appProfile.proof ? `Proof point: ${input.appProfile.proof}.` : '',
      input.appProfile.tone ? `Desired tone: ${input.appProfile.tone}.` : '',
      input.appProfile.markets ? `Target markets: ${input.appProfile.markets}.` : '',
      `Tone: ${input.brandVoice.tone}. Casing: ALL CAPS.`,
      'For EACH screenshot, in the given order, write a two-line headline: line1 = setup, line2 = payoff. <= 4 words per line.',
      'Make the whole set feel like ONE cohesive campaign. Put the most compelling screen first via "order".',
      `NEVER use any of these tokens: ${banned.join('  ')}. No trailing punctuation, no em dashes, no clichés like "in seconds" or "for real life".`,
      'Return JSON exactly: {"order":["id",...],"slides":[{"screenshotId":"id","line1":"...","line2":"..."}]}',
    ].filter(Boolean).join('\n')

    const content: any[] = [{ type: 'text', text: rules }]
    for (const sc of input.screenshots) {
      content.push({ type: 'text', text: `screenshot id: ${sc.id}${sc.label ? ` (file: ${sc.label})` : ''}` })
      content.push({ type: 'image_url', image_url: { url: sc.image } })
    }

    const res = await fetch(`${this.opts.baseUrl ?? 'https://api.openai.com/v1'}/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${this.opts.apiKey}` },
      body: JSON.stringify({
        model, temperature: 0.7, response_format: { type: 'json_object' },
        messages: [{ role: 'system', content: system }, { role: 'user', content }],
      }),
    })
    if (!res.ok) throw new Error(`AI request failed (${res.status}): ${await res.text()}`)
    const data: any = await res.json()
    const parsed = JSON.parse(data?.choices?.[0]?.message?.content ?? '{}')
    const slides: DirectorSlideCopy[] = (parsed.slides ?? []).map((x: any) => ({
      screenshotId: String(x.screenshotId),
      headline: { line1: strip(String(x.line1 ?? ''), banned), line2: strip(String(x.line2 ?? ''), banned) },
    }))
    return {
      order: parsed.order ?? input.screenshots.map((s) => s.id),
      slides,
      notes: [`Generated by OpenAIDirector (${model})`],
    }
  }

  // N distinct two-line options for ONE screenshot (for the studio's "Options" button).
  async options(
    screenshot: { id: string; image: string; label?: string },
    banned: string[], appName: string, count = 3,
  ): Promise<{ line1: string; line2: string }[]> {
    const model = this.opts.model ?? 'gpt-4o-mini'
    const rules = [
      `App: ${appName}.`,
      `Write ${count} DISTINCT two-line store headline options for THIS one screenshot. line1 = setup, line2 = payoff. 4 words max per line. ALL CAPS.`,
      `Never use these tokens: ${banned.join('  ')}. No trailing punctuation, no em dashes.`,
      'Return JSON exactly: {"options":[{"line1":"...","line2":"..."}]}',
    ].join('\n')
    const content: any[] = [{ type: 'text', text: rules }, { type: 'image_url', image_url: { url: screenshot.image } }]
    const res = await fetch(`${this.opts.baseUrl ?? 'https://api.openai.com/v1'}/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${this.opts.apiKey}` },
      body: JSON.stringify({ model, temperature: 0.9, response_format: { type: 'json_object' },
        messages: [{ role: 'system', content: 'You are a senior App Store copywriter. Reply with JSON only.' }, { role: 'user', content }] }),
    })
    if (!res.ok) throw new Error(`AI request failed (${res.status}): ${await res.text()}`)
    const data: any = await res.json()
    const parsed = JSON.parse(data?.choices?.[0]?.message?.content ?? '{}')
    return (parsed.options ?? []).slice(0, count).map((o: any) => ({ line1: strip(String(o.line1 ?? ''), banned), line2: strip(String(o.line2 ?? ''), banned) }))
  }
}


function up(s: string): string { return (s || '').toUpperCase() }

// BYOK translation of a headline set into multiple locales (ALL CAPS, length-aware).
export async function localizeHeadlines(
  items: { id: string; line1: string; line2: string }[], locales: string[], opts: OpenAIOptions,
): Promise<Record<string, Record<string, { line1: string; line2: string }>>> {
  const model = opts.model ?? 'gpt-4o-mini'
  const system = 'You translate short app-store screenshot headlines. Reply with JSON only.'
  const user =
    `Translate these ALL-CAPS two-line headlines into each locale: ${locales.join(', ')}.\n` +
    `Keep them ALL CAPS, punchy, and roughly the same length to avoid overflow. Do not translate brand or product names.\n` +
    items.map((it) => `- id "${it.id}": "${it.line1}" / "${it.line2}"`).join('\n') +
    `\nReturn JSON exactly: {"<locale>": {"<id>": {"line1":"...","line2":"..."}}}`
  const res = await fetch(`${opts.baseUrl ?? 'https://api.openai.com/v1'}/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${opts.apiKey}` },
    body: JSON.stringify({ model, temperature: 0.3, response_format: { type: 'json_object' },
      messages: [{ role: 'system', content: system }, { role: 'user', content: user }] }),
  })
  if (!res.ok) throw new Error(`Translation failed (${res.status}): ${await res.text()}`)
  const data: any = await res.json()
  const parsed = JSON.parse(data?.choices?.[0]?.message?.content ?? '{}')
  const out: Record<string, Record<string, { line1: string; line2: string }>> = {}
  for (const loc of locales) {
    out[loc] = {}
    const block = parsed[loc] ?? {}
    for (const it of items) {
      const v = block[it.id] ?? {}
      out[loc][it.id] = { line1: up(String(v.line1 ?? it.line1)), line2: up(String(v.line2 ?? it.line2)) }
    }
  }
  return out
}
